"""empty message

Revision ID: 693a0d9b475e
Revises:
Create Date: 2024-09-14 17:32:30.077479

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "693a0d9b475e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "level",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_level_id"), "level", ["id"], unique=False)
    op.create_table("player", sa.Column("id", sa.UUID(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_player_id"), "player", ["id"], unique=False)
    op.create_table(
        "prize",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prize_id"), "prize", ["id"], unique=False)
    op.create_table(
        "playerlevel",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("level_id", sa.UUID(), nullable=False),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("score >= 0"),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["level.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playerlevel_id"), "playerlevel", ["id"], unique=False)
    op.create_index(op.f("ix_playerlevel_level_id"), "playerlevel", ["level_id"], unique=False)
    op.create_index(op.f("ix_playerlevel_player_id"), "playerlevel", ["player_id"], unique=False)
    op.create_table(
        "levelprize",
        sa.Column("received", sa.DateTime(), nullable=True),
        sa.Column("prize_id", sa.UUID(), nullable=False),
        sa.Column("player_level_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_level_id"],
            ["playerlevel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prize_id"],
            ["prize.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_levelprize_id"), "levelprize", ["id"], unique=False)
    op.create_index(op.f("ix_levelprize_player_level_id"), "levelprize", ["player_level_id"], unique=False)
    op.create_index(op.f("ix_levelprize_prize_id"), "levelprize", ["prize_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_levelprize_prize_id"), table_name="levelprize")
    op.drop_index(op.f("ix_levelprize_player_level_id"), table_name="levelprize")
    op.drop_index(op.f("ix_levelprize_id"), table_name="levelprize")
    op.drop_table("levelprize")
    op.drop_index(op.f("ix_playerlevel_player_id"), table_name="playerlevel")
    op.drop_index(op.f("ix_playerlevel_level_id"), table_name="playerlevel")
    op.drop_index(op.f("ix_playerlevel_id"), table_name="playerlevel")
    op.drop_table("playerlevel")
    op.drop_index(op.f("ix_prize_id"), table_name="prize")
    op.drop_table("prize")
    op.drop_index(op.f("ix_player_id"), table_name="player")
    op.drop_table("player")
    op.drop_index(op.f("ix_level_id"), table_name="level")
    op.drop_table("level")
    # ### end Alembic commands ###
